//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbConexion : DbContext
    {
        public DbConexion()
            : base("name=DbConexion")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Profile> Profile { get; set; }
        public virtual DbSet<Redes> Redes { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Type_Image> Type_Image { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<User1_User2> User1_User2 { get; set; }
    }
}
