//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public int id { get; set; }
        public Nullable<System.DateTime> day_of_birth { get; set; }
        public Nullable<int> phone { get; set; }
        public string title { get; set; }
        public string bio { get; set; }
        public string public_email { get; set; }
        public Nullable<int> image_id { get; set; }
        public Nullable<int> redes_id { get; set; }
        public int user_id { get; set; }
        public bool borrado { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual Profile Profile1 { get; set; }
        public virtual Profile Profile2 { get; set; }
        public virtual User User { get; set; }
    }
}
