//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class User1_User2
    {
        public int id { get; set; }
        public Nullable<int> user1_id { get; set; }
        public Nullable<int> user2_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public bool borrado { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
